### ISSUE TITLE
Input of experimental grouping variables?

### ISSUE THREAD

**Issue by LaserKate** [JohnsonHsieh/iNEXT#11]
Hi iNEXT creators,

Great package! I am really enjoying using it and find it very user friendly!

Quick comment or suggestion if it is not yet implemented. Is there any way to input experimental grouping factors before creating the iNEXT object? For example, if you have the following set-up and looking at bacterial community diversity:
1) Healthy group and Diseased group
2) Drug 1 group and Drug 2 group both in Healthy group and Drug 1 group and Drug 2 in Diseased group

Then you could easily facet with ggplot by these different factors because the iNEXT object would already have the experimental grouping variables associated with each sample.

So far I think the iNEXT function only accepts a data.frame with rows as species and columns as samples correct?

Thanks!
cheers,
Kate

**Comment by JohnsonHsieh** [comment]
Hi Kate, thx for using iNEXT :)

The suggestion about experimental grouping design is great. According to current iNEXT version, user could use `dplyr` + `reshape2` packages to generate the experimental design `data.frame`. 

Further, I think a formula-based argument is an ideal solution. If there are a lot of users need this function, I’ll achieve it :)

btw, iNEXT also allows list object. However, we recommand use data.frame object.

BR
Johnson
