### ISSUE TITLE
Uninformative error message in estimateD

### ISSUE THREAD

**Issue by KatharinaGerstner** [JohnsonHsieh/iNEXT#16]
I'd like to estimate coverage-based species richness. I use a vector of abundances:

str(dat.abundance)
 'table' int [1:252(1d)] 598 247 30 42 34 32 37 34 29 33 ...
 - attr(*, "dimnames")=List of 1
  ..$ : chr [1:252] "species1" "species10" "species100" "species101" ...

I get an uninformative error message. What is the reason for this error:
estimateD(dat.abundance, "abundance", base="coverage", level=NULL, conf=0.95)
Error in invChat(x, datatype, C = level, conf = conf) : 
  object 'out' not found

Thanks for helping!

**Comment by daniel-hartman** [comment]
Hello Katharina,

Have you tried formatting your data as a data frame?  Maybe check the data provided in the package,
```{r}
data(bird)
print(bird)
```

A data frame with species as row names and sites as column names works well for me.

Dan
