### ISSUE TITLE
How to reduce running time of iNEXT code

### ISSUE THREAD

**Issue by mohammad4458** [JohnsonHsieh/iNEXT#21]
Hi Johnson
thanks for the iNEXT package. It is very useful in comparing site diversities in marine environment.  However, it tends to have long runtimes when using `iNEXT()` for my data (about 24 hours). Is there any way to reduce running time?
Thanks in advance
Mohammad

**Comment by JohnsonHsieh** [comment]
Hi Mohammad,
The `iNEXT()` function allows `size` argument to  choose an integer vector of sample sizes (number of individuals or sampling units) to compute R/E curve.

Before we provide parallel computing version, you could use some parallel computational package (e.g. `foreach`) to save computing time.

BR
Johnson
