### ISSUE TITLE
Baffling Error Message

### ISSUE THREAD

**Issue by mycid** [JohnsonHsieh/iNEXT#3]
Hello,

I've been struggling to apply this package to my dataset in R. When I run the example data: ant$h500m, as the data input in function  iNEXT:
function (x, q = 0, datatype = "abundance", size = NULL, endpoint = NULL, 
    knots = 40, se = TRUE, nboot = 50)  (from the most recent version of the iNEXT package) 

everything works fine. But when I run my data (shown below) 
The first number of the list is the # of samples. The other values are the abundances for each species sampled. 
1]   190    80    80   560 12620 14480    80  7160  4400    80    80   160   200   200
[15]   240  2400  1780  2800  2240   240    80  5400   200   160   280   560 12414 13600
[29] 10260  2820  1000   820  1460   820   100  1800   200   980   280   100  2440   600
[43]   200   300 10200   800    80  1440  1800  1040   400   600  7440   200  1740   500
[57]  2900   920   300   200  6340 14800  2580   320 10112   240   320   320  4460   860
[71]   580 34520
> class(AbundInf)
[1] "numeric"

I receive the following error message: Error in iNEXT.Sam(Spec = x, q = q, t = size, endpoint = ifelse(is.null(endpoint),  : invalid data structure!, first element should be number of sampling units

For all appearances my data looks the same as the example data yet it does not work. I've looked through the function and I don't understand how this error message is being generated because I can't find it in the function. There also is no iNEXT.Sam function to be found in this updated iNEXT package.  Finally, I don't understand how the function is determining that the first element is not the number of sampling units when it just as well could be the next element. 

Can you help me use the iNEXT package correctly so I can continue analyzing my data?

**Comment by JohnsonHsieh** [comment]
Hi mycid,
It seems that the iNEXT document don't look very clear.

For the incidence frequencies data (iNEXT input format), it should be convert from the species by sites presence-absence matrix. Each element in the matrix should be 0 or 1. Therefore, the incidence frequencies for species are row-sums of the matrix. All the incidence frequencies should be smaller than total number of samples.

Recently, I provide a new function `as.incfreq` to transform incidence raw data (a species by sites presence-absence matrix) to incidence frequencies data (iNEXT input format, a row-sum frequencies vector contains total number of sampling units).

**Comment by ndimhypervol** [comment]
I was just having the same problem, and now I understand better what you mean by frequencies. Can you please update the vignette to emphasize that the frequencies should be calculated from a presence-absence matrix? I was previously using abundances per sampling unit until I saw this. Also, it would be great if you could advertise your conversion function in the vignette as well. Thanks!

**Comment by Oswaldo1978** [comment]
Hello everyone. Right now I am parsing my data with the Inext package but I am getting this error. Please could you tell me how you definitively fixed this error and how the data could be organized in an excel sheet, then take it to R. Thanks for your help.
