### ISSUE TITLE
Triple the size of reference sample?!

### ISSUE THREAD

**Issue by anabbi** [JohnsonHsieh/iNEXT#33]
Hello,

I would like to change the default of endpoint parameter to triple the size of reference sample. I pass a list to iNEXT containing abundance data that looks exactly like spider data. I would like to compute the endpoint per site.

Thanks for your help

**Comment by JohnsonHsieh** [comment]
Hi @anabbi 
The `endpoint` parameter do NOT allow vectorized computation, you need to use `for-loop`

```
data(spider)
endpt <- c(300, 400) # set a vector of endpotins
out <- list()
for(i in 1:length(spider)){
  out[[i]] <- iNEXT(spider[[i]], q=0, datatype = "abundance", endpoint = endpt[i])
}

names(out) <- names(spider) # set names for list object which could be ignored
out # show output
```
