### ISSUE TITLE
iNEXT no longer on CRAN

### ISSUE THREAD

**Issue by nick-youngblut** [JohnsonHsieh/iNEXT#45]
It appears that `iNEXT` is no longer on CRAN: https://cran.r-project.org/web/packages/iNEXT/index.html

```
Package ‘iNEXT’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2020-01-11 as check problems were not corrected in time.
```

**Comment by JohnsonHsieh** [comment]
Fix and update to v 2.0.20 
https://cran.r-project.org/web/packages/iNEXT/index.html
