### ISSUE TITLE
Issues with estimateD in INEXT package

### ISSUE THREAD

**Issue by Lizzie-fi** [JohnsonHsieh/iNEXT#5]
Hello,
I've been using your package extensively on my datasets, but I can't seem to use the estimateD function. Whenever I try to apply it to my own data, the output is always NULL.

I used the following code where site_ab is a data frame of species abundances:

estimateD(site_ab, "abundance", base="coverage", level=NULL)

Any ideas on why it isn't working and how I could fix it?

**Comment by Lizzie-fi** [comment]
I thought that it might help to update R and reinstall the package but when I did this, I got the following error:
 >install_github('JohnsonHsieh/iNEXT')
Downloading GitHub repo JohnsonHsieh/iNEXT@master
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’

I've tried downloading it from CRAN as well, but I still get the same error message.
Is there a way to fix this?

**Comment by JohnsonHsieh** [comment]
Ohh, thanks for report this bug, I'll fix that ASAP,
Currently `estimateD` still work perfectly for `list` object, so you can use the following commands:

```
site_sp <- read.csv("site_sp.csv")
list_sp <- lapply(site_sp, c) # convert data.frame to list
estimateD(list_sp, "abundance", base="size", level=NULL)
```
Again, thx for report this bug :)

**Comment by Lizzie-fi** [comment]
Hi Johnson,


That's absolutely perfect, thank you so much!


All the best,
Lizzie


________________________________
