### ISSUE TITLE
iNEXT for q = 1 not completing

### ISSUE THREAD

**Issue by mcjudd** [JohnsonHsieh/iNEXT#6]
Hello,

Has the iNEXT function been tested for large datasets? I'm using the abundance datatype to compare 9 populations with ~ 500,000 observations total and have let the function (with q = c(0, 1) specified) run overnight without it completing. I've attempted to step through the iNEXT function using debugonce() to determine possible bottlenecks, but have been unable to determine whether the function has hung up in a loop or simply takes a very long time to complete. Please advise on any solution or helpful troubleshooting techniques.

Thank you,
Mike

**Comment by JohnsonHsieh** [comment]
Hi mcjudd,
In fact, iNEXT don't design for large datasets (specially for q = 1). 
The main reason is the bootstrap variance for rarefaction/extrapolation estimator take too much computing effort and time. 

Currently, an imperfect solutions for large datasets is parallels computing. If I have time, I'll add this features in the next version :)
